name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # --- TAMBAHAN BLOK INI DI SINI ---
    permissions:
      contents: write
    # ------------------------------------

    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Packages
        run: make install
      - name: Train
        run: make train
      - name: Evaluate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval
      - name: Update Branch
        env:
          NAME: ${{ secrets.USER_NAME }}
          EMAIL: ${{ secrets.USER_EMAIL }}
        run: make update-branch USER_NAME=$NAME USER_EMAIL=$EMAIL
